###GET PRODUCTS

GET http://localhost:8000/api/products

###GET SINGLE PRODUCT
GET http://localhost:8000/api/product/6140cb255597611826b98ad8

###CREATE PRODUCT
POST http://localhost:8000/api/products/new
Content-Type: application/json


{
  "title":"PS5",
  "price":99,
  "description":"Last generation console sonny brand"
}

###UPDATE PRODUCT
PUT http://localhost:8000/api/products/update/61402052a22e662eaad4433c
Content-Type: application/json

{
  "title":"PS5",
  "price":489,
  "description":"Last generation console sonny brand"

}

###DELETE PRODUCT
DELETE http://localhost:8000/api/products/delete/6142735bee4b0cc4cf6f8336