###GET PRODUCTS

GET http://localhost:8000/api/products

###GET SINGLE PRODUCT
GET http://localhost:8000/api/product/61424238fd80448710e3b540

###CREATE PRODUCT
POST http://localhost:8000/api/products/new
Content-Type: application/json


{
  "title":"PS5",
  "price":99,
  "description":"Last generation console sonny brand"
}

